preload = ~/.config/wallpapers/wallpaper1/2-cat-waves-mocha.png
# Replace the monitor name below with your output (run: hyprctl monitors)
# Common values: eDP-1, eDP-2, HDMI-A-1, DP-1, DisplayPort-1
wallpaper = ,~/.config/wallpapers/wallpaper1/2-cat-waves-mocha.png
splash = false
ipc = on
