exec-once = awww-daemon
exec-once = sleep 2 && ~/.config/hypr/scripts/wallpaper.sh init
exec-once = ~/.config/hypr/scripts/wallpaper-daemon.sh
exec-once = waybar
exec-once = sleep 2 && /usr/lib/polkit-kde-authentication-agent-1
exec-once = dunst
exec-once = $HOME/.config/waybar/scripts/battery-warn.sh
