windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = cachyos-hello-float

    match:class = org.cachyos.hello

    float = yes
    center = yes
}

windowrule {
    name = fastfetch-popup

    match:class = fastfetch-popup

    float = yes
    center = yes
    size = 700 420
}

windowrule {
    name = btop-float

    match:class = btop

    float = yes
    center = yes
    size = 700 470
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = pavucontrol-float

    match:class = pavucontrol

    float = yes
    size = 600 400
    center = true
}

windowrule {
    name = sensors-popup

    match:class = sensors-popup

    float = yes
    size = 520 600
    center = true
}

windowrule {
    name = network-settings

    match:class = network-settings

    float = yes
    size = 600 400
    center = true
}

windowrule {
    name = pkg-install

    match:class = pkg-install

    float = yes
    center = yes
    size = 700 500
}

windowrule {
    name = hyprland-share-picker

    match:class = hyprland-share-picker

    float = yes
    center = true
}

windowrule {
    name = file-picker-float

    match:class = xdg-desktop-portal-gtk

    float = yes
    center = yes
    size = 900 600
}

windowrule {
    name = reddit-downloader

    match:class = reddit-downloader

    float = yes
    center = yes
    size = 600 400
}
